apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-billing-exporter 
spec:
  selector:
    matchLabels:
      app: oci-billing-exporter
  template:
    metadata:
      labels:
        app: oci-billing-exporter
    spec:
      containers:
      - name: exporter
        image: westelh/oci-billing-exporter:0.0.1-snapshot
        args: ["instance", "--tenancy", "ocid1.tenancy.oc1..aaaaaaaamkwobhnc6grgig2mde565ehr2hkj4es5yxzgttlveortczezso2a", "--region", "ap-tokyo-1"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
