apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-billing-exporter 
spec:
  selector:
    matchLabels:
      app: oci-billing-exporter
  template:
    metadata:
      labels:
        app: oci-billing-exporter
    spec:
      containers:
      - name: exporter
        image: westelh/oci-billing-exporter:0.0.2
        args: ["instance", "--tenancy", "ocid1.tenancy.oc1..aaaaaaaamkwobhnc6grgig2mde565ehr2hkj4es5yxzgttlveortczezso2a"]
        ports:
        - containerPort: 8080
